### ISSUE TITLE
ImportError: cannot import name QVariant

### ISSUE THREAD

**Issue by InukPhysiker** [slaclab/timechart#52]
[Timechart] [username@SL7 bin]$ ./timechart
Traceback (most recent call last):
  File "./timechart", line 11, in <module>
    load_entry_point('timechart==1.2.2', 'gui_scripts', 'timechart')()
  File "/home/username/virtualenvironment/Timechart/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/username/virtualenvironment/Timechart/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/home/username/virtualenvironment/Timechart/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/home/username/virtualenvironment/Timechart/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/username/virtualenvironment/Timechart/lib/python2.7/site-packages/timechart-1.2.2-py2.7.egg/timechart_launcher/main.py", line 16, in <module>
    from pydm.application import PyDMApplication
  File "/home/username/virtualenvironment/Timechart/lib/python2.7/site-packages/pydm/__init__.py", line 1, in <module>
    from .application import PyDMApplication
  File "/home/username/virtualenvironment/Timechart/lib/python2.7/site-packages/pydm/application.py", line 22, in <module>
    from .main_window import PyDMMainWindow
  File "/home/username/virtualenvironment/Timechart/lib/python2.7/site-packages/pydm/main_window.py", line 8, in <module>
    from .connection_inspector import ConnectionInspector
  File "/home/username/virtualenvironment/Timechart/lib/python2.7/site-packages/pydm/connection_inspector/__init__.py", line 1, in <module>
    from .connection_inspector import ConnectionInspector
  File "/home/username/virtualenvironment/Timechart/lib/python2.7/site-packages/pydm/connection_inspector/connection_inspector.py", line 5, in <module>
    from .connection_table_model import ConnectionTableModel
  File "/home/username/virtualenvironment/Timechart/lib/python2.7/site-packages/pydm/connection_inspector/connection_table_model.py", line 1, in <module>
    from qtpy.QtCore import QAbstractTableModel, Qt, QModelIndex, QVariant, QTimer, Slot

**Comment by hhslepicka** [comment]
Hi @InukPhysiker ,

Do you mind to give us a bit more of detail about your environment?
I see Python 2.7... which version of Qt and which Python wrapper are you using (PyQt 5, PySide2, ...)?

**Comment by InukPhysiker** [comment]
Qt 4.8
pyside-1.2.4

The following prerequisites were installed:

PyDM-1.6.4
numpy-1.16.1
pyepics-3.3.3
pyqtgraph-0.10.0
qtpy-1.6.0
six-1.12.0
